language: cpp
compiler:
  - clang
before_install:
  - pyenv install 3.6.0
  - pip install requests
script:
  - g++ -std=c++11 -o TestBinary -fprofile-arcs -ftest-coverage test/test_index.cpp
  - ./TestBinary
  - gcov -o . test/test_index.cpp
  - bash <(curl -s https://codecov.io/bash)
  - python request.py
