name: Github Actions Go Standard
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  standard-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Before Install
        run: |
          pip install requests
          sudo apt-get install g++
      - name: Run Tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
          EXPECTED_COVERAGE: ${{ secrets.EXPECTED_COVERAGE }}
        run: |
          g++ -std=c++11 -o TestBinary -fprofile-arcs -ftest-coverage test/test_index.cpp
          ./TestBinary
          gcov -o . test/test_index.cpp
          bash <(curl -s https://codecov.io/bash)
          python request.py
      - name: Upstream to Standards
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: ${{ github.event_name == 'push'}}
        run: |
          ./upstream.sh
